name: .NET CI
on:
  push:
    branches:
      - "**" # Run on all branches push
  pull_request:
    branches:
      - "main" # Run on pull requests to the main branch

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true # Cancel previous runs if new one is triggered

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0.100-preview.4.24267.6"
          include-prerelease: true

      - name: Restore dependencies
        run: dotnet restore rosterMate.sln

      - name: Build Solution
        run: dotnet build rosterMate.sln --configuration Release --no-restore

      - name: Run Tests
        run: dotnet test rosterMate.sln --configuration Release --no-build --verbosity normal
